### ISSUE TITLE
Poco::Net::NetException "SSL Exception: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry"

### ISSUE THREAD

**Issue by npennec** [pocoproject/poco#1160]
POCO version = 1.6.1.0

Calling the following method sometimes throw a Poco::Net::NetException "SSL Exception: error:1409F07F:SSL routines:ssl3_write_pending:bad write retry" :
Poco::Net::WebSocket::sendFrame(const void \* buffer, int length, int flags)

this occurred with flags = WebSocket::FRAME_FLAG_FIN | WebSocket::FRAME_FLAG_PING
or flags = WebSocket::FRAME_TEXT

See an interesting related URL to solve such exceptions when calling SSL_write() :
http://stackoverflow.com/questions/2997218/why-am-i-getting-error1409f07fssl-routinesssl3-write-pending-bad-write-retr

**Comment by obiltschnig** [comment]
What version of OpenSSL are you using?
Do you have a complete example (client + server) to reproduce this?

**Comment by npennec** [comment]
openSSL version : 1.0.2d

Hmmm, difficult for me to give a complete client-serveur exemple;
It occurs in a serveur context : Poco is used to manage web sockets.
messages are sent to the clients, with various size messages (8 bytes "heartbeat" or "keepalive" messages and messages containing around 4000 bytes of data)
The hexa flags values are 0x81 or 0x89.

When the problem appears on a connection :
- first, a Poco::TimeoutException is thrown by the (same) samePoco::Net::WebSocket::sendFrame() call
- then, it seems to persist despite many retries until the connection is closed / given up.

**Comment by obiltschnig** [comment]
Thanks, that info helps. I have an idea what may go wrong. Seems that OpenSSL now can return SSL_ERROR_WANT_READ and SSL_ERROR_WANT_WRITE even for blocking sockets, and we need to handle this correctly.
A first workaround is to close the connection if you get a Poco::TimeoutException, as you won't be able to recover from that.

**Comment by npennec** [comment]
Thank you very much for your help !

**Comment by obiltschnig** [comment]
I've committed a fix to 1.6.2 and develop branches. Could you give it a try?

**Comment by obiltschnig** [comment]
@npennec I'd like to close this for the 1.7.0 release. Could you please give feedback whether this fixes your issue by March 2? Thank you!

**Comment by npennec** [comment]
Thanks, your fix has been taken into account.
It should be under test tomorrow (March 1st)

**Comment by npennec** [comment]
yes, we now close the webSocket when a Poco::TimeoutException occurs.
but it has not been tested yet

**Comment by npennec** [comment]
The fix for Poco 1.6.2 has been under test during the last weekend :
webSockets are now closed as soon as a Poco::TimeoutException occurs, but we still have some Poco::Net::NetException on calling :
 - Poco::Net::WebSocket::safeSendFrame() even without Poco::TimeoutException
 - Poco::Net::WebSocket::shutdown() just after Poco::TimeoutException, when trying to close the hopeless sending connection
=> After a Poco::TimeoutException, is the webSocket fully unusable, even for calling a shutdown() ?

**Comment by obiltschnig** [comment]
That's to be expected, because for a WebSocket, shutdown() attempts to send a WS Close notification frame (this is different from an ordinary socket). Which of course does not work, since OpenSSL internal state is messed up. The only safe thing to do after a TimeoutException is to call close().

**Comment by npennec** [comment]
Thanks, i will use close() instead of shutdown() after a poco::TimeoutException

**Comment by GalloTeo** [comment]
Hello obiltschnig, 
i actually updated poco to 1.78 p3  and using openSSL 1.0.2g but i am still getting SSL Exception msg error:1409F07F:SSL routines:ssl3_write_pending:bad write retry

i tried to play with the timeout of the sending and the receiving, but without any success. 
did you experienced again the problem or do you have any further resolution we can test ? 

thank you in advance 

Teo
