### ISSUE TITLE
Poco::Mysql does not build with MySQL 8.0+

### ISSUE THREAD

**Issue by nnmm79** [pocoproject/poco#2744]
From quick google search it appers that the problem is that in new version of mySQL they removed my_bool tape and MYSQL_SECURE_AUTH option, but Poco is still refereencing both of them.

Tested with latest vcpkg version:
Commit hash:	f9fedc930cf36ce6cec69a3d09879b3c7f23eb0b

**Comment by Whissi** [comment]
There are multiple issues. Build log of current poco-1.9.2 against mysql-connector-c-8.0.17:
```

[528/572] /usr/bin/x86_64-pc-linux-gnu-g++ -DMySQL_EXPORTS -DNO_TCL -DPOCO_ENABLE_CPP11 -DPOCO_ENABLE_CPP14 -DPOCO_HAVE_FD_EPOLL -DPOCO_NO_AUTOMATIC_LIBS -DPOCO_OS_FAMILY_UNIX -DPOCO_UNBUNDLED -DTHREADSAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_REENTRANT -D_THREAD_SAFE -D_XOPEN_SOURCE=500 -I/usr/include/mysql -I/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include -I/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src -I/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Foundation/include -I/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/include  -DNDEBUG -O2 -pipe -march=znver1 -mtune=znver1 -fPIC   -std=gnu++14 -MD -MT Data/MySQL/CMakeFiles/DataMySQL.dir/src/Binder.cpp.o -MF Data/MySQL/CMakeFiles/DataMySQL.dir/src/Binder.cpp.o.d -o Data/MySQL/CMakeFiles/DataMySQL.dir/src/Binder.cpp.o -c /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp
FAILED: Data/MySQL/CMakeFiles/DataMySQL.dir/src/Binder.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DMySQL_EXPORTS -DNO_TCL -DPOCO_ENABLE_CPP11 -DPOCO_ENABLE_CPP14 -DPOCO_HAVE_FD_EPOLL -DPOCO_NO_AUTOMATIC_LIBS -DPOCO_OS_FAMILY_UNIX -DPOCO_UNBUNDLED -DTHREADSAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_REENTRANT -D_THREAD_SAFE -D_XOPEN_SOURCE=500 -I/usr/include/mysql -I/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include -I/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src -I/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Foundation/include -I/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/include  -DNDEBUG -O2 -pipe -march=znver1 -mtune=znver1 -fPIC   -std=gnu++14 -MD -MT Data/MySQL/CMakeFiles/DataMySQL.dir/src/Binder.cpp.o -MF Data/MySQL/CMakeFiles/DataMySQL.dir/src/Binder.cpp.o.d -o Data/MySQL/CMakeFiles/DataMySQL.dir/src/Binder.cpp.o -c /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp
In file included from /usr/include/mysql/mysql.h:84,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql/client_plugin.h:108:8: error: using typedef-name ‘MYSQL’ after ‘struct’
  108 | struct MYSQL;
      |        ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:26:25: note: ‘MYSQL’ has a previous declaration here
   26 | typedef struct st_mysql MYSQL;
      |                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql/client_plugin.h:115:58: error: using typedef-name ‘MYSQL’ after ‘struct’
  115 |   int (*authenticate_user)(MYSQL_PLUGIN_VIO *vio, struct MYSQL *mysql);
      |                                                          ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:26:25: note: ‘MYSQL’ has a previous declaration here
   26 | typedef struct st_mysql MYSQL;
      |                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql/client_plugin.h:117:65: error: using typedef-name ‘MYSQL’ after ‘struct’
  117 |                                                          struct MYSQL *mysql,
      |                                                                 ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:26:25: note: ‘MYSQL’ has a previous declaration here
   26 | typedef struct st_mysql MYSQL;
      |                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql/client_plugin.h:139:57: error: using typedef-name ‘MYSQL’ after ‘struct’
  139 | struct st_mysql_client_plugin *mysql_load_plugin(struct MYSQL *mysql,
      |                                                         ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:26:25: note: ‘MYSQL’ has a previous declaration here
   26 | typedef struct st_mysql MYSQL;
      |                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql/client_plugin.h:159:59: error: using typedef-name ‘MYSQL’ after ‘struct’
  159 | struct st_mysql_client_plugin *mysql_load_plugin_v(struct MYSQL *mysql,
      |                                                           ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:26:25: note: ‘MYSQL’ has a previous declaration here
   26 | typedef struct st_mysql MYSQL;
      |                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql/client_plugin.h:173:64: error: using typedef-name ‘MYSQL’ after ‘struct’
  173 | struct st_mysql_client_plugin *mysql_client_find_plugin(struct MYSQL *mysql,
      |                                                                ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:26:25: note: ‘MYSQL’ has a previous declaration here
   26 | typedef struct st_mysql MYSQL;
      |                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql/client_plugin.h:192:12: error: using typedef-name ‘MYSQL’ after ‘struct’
  192 |     struct MYSQL *mysql, struct st_mysql_client_plugin *plugin);
      |            ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:26:25: note: ‘MYSQL’ has a previous declaration here
   26 | typedef struct st_mysql MYSQL;
      |                         ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql.h:292:8: error: using typedef-name ‘MYSQL_STMT’ after ‘struct’
  292 | struct MYSQL_STMT;
      |        ^~~~~~~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:27:30: note: ‘MYSQL_STMT’ has a previous declaration here
   27 | typedef struct st_mysql_stmt MYSQL_STMT;
      |                              ^~~~~~~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql.h:294:16: error: using typedef-name ‘MYSQL’ after ‘struct’
  294 | typedef struct MYSQL {
      |                ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:26:25: note: ‘MYSQL’ has a previous declaration here
   26 | typedef struct st_mysql MYSQL;
      |                         ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql.h:332:3: error: conflicting declaration ‘typedef int MYSQL’
  332 | } MYSQL;
      |   ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:26:25: note: previous declaration as ‘typedef struct st_mysql MYSQL’
   26 | typedef struct st_mysql MYSQL;
      |                         ^~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql.h:665:16: error: using typedef-name ‘MYSQL_STMT’ after ‘struct’
  665 | typedef struct MYSQL_STMT {
      |                ^~~~~~~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:27:30: note: ‘MYSQL_STMT’ has a previous declaration here
   27 | typedef struct st_mysql_stmt MYSQL_STMT;
      |                              ^~~~~~~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:24,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/usr/include/mysql/mysql.h:708:3: error: conflicting declaration ‘typedef int MYSQL_STMT’
  708 | } MYSQL_STMT;
      |   ^~~~~~~~~~
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/Binder.h:23,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/Binder.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLException.h:27:30: note: previous declaration as ‘typedef struct st_mysql_stmt MYSQL_STMT’
   27 | typedef struct st_mysql_stmt MYSQL_STMT;
      |                              ^~~~~~~~~~
[...]
In file included from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/SessionImpl.h:25,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/MySQLStatementImpl.h:21,
                 from /var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/src/MySQLStatementImpl.cpp:15:
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/ResultMetadata.h:62:14: error: ‘my_bool’ was not declared in this scope; did you mean ‘bool’?
   62 |  std::vector<my_bool>       _isNull;
      |              ^~~~~~~
      |              bool
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/ResultMetadata.h:62:21: error: template argument 1 is invalid
   62 |  std::vector<my_bool>       _isNull;
      |                     ^
/var/tmp/portage/dev-libs/poco-1.9.2/work/poco-poco-1.9.2-release/Data/MySQL/include/Poco/Data/MySQL/ResultMetadata.h:62:21: error: template argument 2 is invalid
ninja: build stopped: subcommand failed.
```

**Comment by obiltschnig** [comment]
Where do you get said Connector/C 8.0 client? The MySQL 8 installer for Windows still has Connector/C 6.1 included, with which Data/MySQL builds fine.

**Comment by Whissi** [comment]
Use Gentoo Linux :-)

https://dev.mysql.com/downloads/connector/cpp/

**Comment by obiltschnig** [comment]
Something's strange here. All the Connector/C versions I find end at 6.1. And the Connector/C++ packages don't contain the old libmysql headers (mysql.h, etc.).

**Comment by obiltschnig** [comment]
Ok, if you want this fixed in 1.10 send a pull request; I'm not spending more time on it for now.

**Comment by nnmm79** [comment]
> Where do you get said Connector/C 8.0 client? The MySQL 8 installer for Windows still has Connector/C 6.1 included, with which Data/MySQL builds fine.

I was using vcpkg package manager on windows (https://github.com/Microsoft/vcpkg), which makes this problem especially problematic for my use case, since that package manager does not allow me to mix and match different library versions. 

I retested and the problem persists with vcpkg Commit hash:	300e21d59ebfe42e118cf4e97887f0680fbcfa2f

poco version included in this build is 1.9.2 and mysqllib version is 8.0.4-4

If you need any other info from me do not hesitate to ask.
