### ISSUE TITLE
Wrong install location for cmake config files on Ubuntu

### ISSUE THREAD

**Issue by Krzmbrzl** [pocoproject/poco#3244]
First off: I am not entirely sure whether this is an issue with Poco itself or only with the way it now gets packaged on recent versions of Ubuntu.

Trying to locate the Poco libraries via a regular `find_package` command fails starting from Ubuntu Groovy (20.10). It still works fine on Ubuntu focal (20.04).
```cmake
find_package(Poco COMPONENTS Zip)
```

Presumably this is because in 20.04, the cmake config files are installed to e.g. `/usr/lib/cmake/Poco/PocoConfig.cmake` ([source](https://packages.ubuntu.com/focal/amd64/libpoco-dev/filelist)) whereas on 20.10, they are installed to `/usr/lib/x86_64-linux-gnu/cmake/cmake/Poco/PocoConfig.cmake`([source](https://packages.ubuntu.com/groovy/amd64/libpoco-dev/filelist)). Note the `cmake/cmake` part in that path, which I believe is one `cmake` dir too much for it to work.

Did you perhaps make any changes to the install locations that could have caused this issue or is this something the Ubuntu packagers have changed on their own?

**Comment by Bjoe** [comment]
@Krzmbrzl Right, this is the wrong directory

I must verify on which site this is going wrong....

**Comment by Bjoe** [comment]
It might be, this is the problem we set [PocoConfigPackageLocation](https://github.com/pocoproject/poco/blob/3fc3e5f5b8462f7666952b43381383a79b8b5d92/cmake/PocoMacros.cmake#L236)
We should not do this. The correct location is set by cmake. Cmake know on which platform it is building the project and put the config-moduls in the correct directory.
But I need to verify this. Btw. the debian package has also some interesting patches :-)

**Comment by jayvdb** [comment]
I've noted this problem in [debian bugreport 1000656](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000656) along with another problem effecting Debian/Ubuntu/etc wrt cmake finding pcre.

**Comment by jspricke** [comment]
This should be fixed in 1.11.0-3 in Debian unstable. Sorry for the trouble.

**Comment by jayvdb** [comment]
@jspricke , I think the pcre problem reported in [debian bugreport 1000656](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000656) is yet to be addressed.  One solution is to install https://github.com/pocoproject/poco/blob/master/cmake/FindPCRE.cmake in the Poco cmake directory.

Also https://packages.debian.org/sid/libpoco-dev is still showing `1.11.0-2`, containing the double cmake/cmake path in `/usr/lib/x86_64-linux-gnu/cmake/cmake/Poco`.  Is that because of the pipeline failure at https://salsa.debian.org/debian/poco/-/pipelines/318257 , or just a usual delay in the new release propagating to all the various systems?

**Comment by jspricke** [comment]
***@***.*** , I think the pcre problem reported in [debian bugreport 1000656](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000656) is yet to be addressed.  One solution is to install https://github.com/pocoproject/poco/blob/master/cmake/FindPCRE.cmake in the Poco cmake directory.

It was addressed in the upload.

>Also https://packages.debian.org/sid/libpoco-dev is still showing `1.11.0-2`, containing the double cmake/cmake path in `/usr/lib/x86_64-linux-gnu/cmake/cmake/Poco`.

Debian unstable is updated 4 times per day, it ran in the meantime and 
the page shows the new package now.

>Is that because of the pipeline failure at https://salsa.debian.org/debian/poco/-/pipelines/318257 , or just a usual delay in the new release propagating to all the various systems?

CI is unrelated.

**Comment by jayvdb** [comment]
Tested. Both are now fixed! Thanks @jspricke !

**Comment by jayvdb** [comment]
Can we expect this might make it into stable(bullseye), where `libpoco-dev` is at `1.10.0-6`?

**Comment by jspricke** [comment]
I've proposed a stable update in https://bugs.debian.org/1000736.

**Comment by jayvdb** [comment]
@jspricke , it looks like you have the green light.

**Comment by jspricke** [comment]
Yes, it was already accepted: https://release.debian.org/proposed-updates/stable.html
And will be part of the next stable release point release on the 18.: https://release.debian.org/

**Comment by jayvdb** [comment]
Thanks for the links - I'm slowly learning the debian processes ;-)

**Comment by jspricke** [comment]
Btw. as the initial bug report was for Ubuntu, maybe someone wants to fill a SRU: https://wiki.ubuntu.com/StableReleaseUpdates

**Comment by jayvdb** [comment]
Now in Debian stable and Ubuntu jammy.
I guess this can be closed now, unless this ticket also wants to track it drifting into a stable Ubuntu.
