### ISSUE TITLE
Failed to build PostgreSQL branch

### ISSUE THREAD

**Issue by astlin** [pocoproject/poco#837]
Failed at building PostgreSQL adapter:

/home/beowulf/soft/poco-PostgreSQL/Data/PostgreSQL/src/SessionImpl.cpp: In member function ‘virtual Poco::Data::StatementImpl\* Poco::Data::PostgreSQL::SessionImpl::createStatementImpl()’:
/home/beowulf/soft/poco-PostgreSQL/Data/PostgreSQL/src/SessionImpl.cpp:194:85: error: invalid new-expression of abstract class type ‘Poco::Data::PostgreSQL::PostgreSQLStatementImpl’
  return dynamic_castPoco::Data::StatementImpl* (new PostgreSQLStatementImpl (_this));
                                                                                     ^
In file included from /home/beowulf/soft/poco-PostgreSQL/Data/PostgreSQL/src/SessionImpl.cpp:39:0:
/home/beowulf/soft/poco-PostgreSQL/Data/PostgreSQL/include/Poco/Data/PostgreSQL/PostgreSQLStatementImpl.h:57:22: note:   because the following virtual functions are pure within ‘Poco::Data::PostgreSQL::PostgreSQLStatementImpl’:
 class PostgreSQL_API PostgreSQLStatementImpl: public Poco::Data::StatementImpl
                      ^
In file included from /home/beowulf/soft/poco-PostgreSQL/Data/PostgreSQL/include/Poco/Data/PostgreSQL/PostgreSQLStatementImpl.h:47:0,
                 from /home/beowulf/soft/poco-PostgreSQL/Data/PostgreSQL/src/SessionImpl.cpp:39:
/home/beowulf/soft/poco-PostgreSQL/Data/include/Poco/Data/StatementImpl.h:172:28: note:     virtual const Poco::Data::MetaColumn& Poco::Data::StatementImpl::metaColumn(std::size_t) const
  virtual const MetaColumn& metaColumn(std::size_t pos) const = 0;
                            ^
Data/PostgreSQL/CMakeFiles/DataPostgreSQL.dir/build.make:192: recipe for target 'Data/PostgreSQL/CMakeFiles/DataPostgreSQL.dir/src/SessionImpl.cpp.o' failed
make[2]: *_\* [Data/PostgreSQL/CMakeFiles/DataPostgreSQL.dir/src/SessionImpl.cpp.o] Error 1
CMakeFiles/Makefile2:728: recipe for target 'Data/PostgreSQL/CMakeFiles/DataPostgreSQL.dir/all' failed
make[1]: **\* [Data/PostgreSQL/CMakeFiles/DataPostgreSQL.dir/all] Error 2

**Comment by intensifi** [comment]
which OS?  which compiler? which version of CMake? Which version of postgresql?  How did you specify the PostgreSQL include and lib directories?

**Comment by astlin** [comment]
OS: Ubuntu 15.04 x64. gcc version 4.9.2, cmake version 3.0.2, postgresql 9.4, libpq + libpq-dev from distro repos. PostgreSQL include and lib directories i set directly in /Data/CMakeLists.txt (set(POSTGRESQL_INCLUDE_DIR "/usr/include/postgresql")) cause it won't find it when running build_cmake.sh.

**Comment by intensifi** [comment]
I'm starting to build a VM now to test in your environment.  I'll try to have resolution by COB Friday.

**Comment by astlin** [comment]
Thank you. Related issue in /Data/CMakeLists.txt:59 there's a check if POSTGRESQL_FOUND is set, but this var is never set anywhere, i suppose PGSQL_FOUND should be used, in /cmake/FindPostgreSQL.cmake:44

**Comment by intensifi** [comment]
For the main issue I have isolated the cause to be a synchronization issue to a code update where a method signature changed.

I have an email into Aleks seeking his counsel on how to fix this. 

For the CMake issue, I'll take a look tonight.

**Comment by intensifi** [comment]
Per Aleks's suggestion I merged the ODBCSybase branch into my local PostgreSQL branch. It built and tested successfully on MacOSX. It is currently building on Windows and your Linux configuration. I'll run the tests when I get home tonight. If all is well I'll check it in (pull request) then.  I have updated the CMake configuration files to try and fix your second issue. I'd appreciate your assistance testing the revised CMake configuration.

**Comment by intensifi** [comment]
Pull request with fixes is pending

**Comment by aleks-f** [comment]
[merged](https://github.com/pocoproject/poco/commit/91197514177993afa74666e96d5365875d8c8062)

**Comment by astlin** [comment]
Thank you. Building with 'make' successful, but build_cmake.sh script still can't find PostgreSQL library "PostgreSQL Support Disabled - no PostgreSQL library".

**Comment by aleks-f** [comment]
@bachp : can you help here? [PostgreSQL](https://github.com/pocoproject/poco/tree/PostgreSQL) branch

**Comment by intensifi** [comment]
This is now fixed.  I would still appreciate @bachp checking my work as I am still a FNG with regard to CMake.

**Comment by bachp** [comment]
I had a look at how you find PostgreSQL.
As far as I know cmake already has a FindPostgreSQL module included.
See: [documentation](https://cmake.org/cmake/help/git-master/module/FindPostgreSQL.html?highlight=postgresql) and [source](https://github.com/Kitware/CMake/blob/master/Modules/FindPostgreSQL.cmake)

So I don't think our own FindPostgreSQL.cmake is necessary. 
@intensifi Could you try to used the module mentioned above instead of the one in the cmake folder?

I also would belive that the CMake provided find module might work on more platforms, but I might be wrong.

**Comment by intensifi** [comment]
Excellent!  I saw a FindMySql.cmake file and assumed I had to write a FindPostgres.cmake.

I verified the FindPostgreSQL.cmake file does exist in my CMake distribution.  I wonder why there is no FindMySQL.cmake file.  I thought that MySQL was more "popular".

My plan for tonight is to remove that file and potentially change my POSTGRESQL_FOUND variable in the outer/calling CMake script - and Test.

I'll let you know if I run into any problems.

Thanks again!

**Comment by intensifi** [comment]
- It works on Windows.  

- Fails on MacOSX when using the Postgres.app distribution

- Will test on Linux tonight.

**Comment by bachp** [comment]
In the worst case we should copy FindPostgreSQL.cmake from upstream and fix it so that it works for MacOS X and the other cases required by Poco.

I (or somebody else) can then try to bring this modifications upstream into CMake.
So somday in the future we can get rid of the copy again.

**Comment by intensifi** [comment]
I will update the FindPostgreSQL.cmake file provided by CMake with fixes for MacOSX.

I verified the provided file works fine on Linux.

**Comment by intensifi** [comment]
I took the CMake FindPostgreSQL.cmake file and updated it to find PostgreSQL properly on MacOSX, Linux and Windows.  Pull request is: #980

**Comment by avosya** [comment]
build_cmake.sh script still can't find PostgreSQL library "PostgreSQL Support Disabled - no PostgreSQL library". 

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Comment by zosrothko** [comment]
If the release poco-1.7.3 is ok for you, there is a private ppa on launchpad
sudo add-apt-repository ppa:zosrothko/poco
sudo apt-get update

**Comment by Bjoe** [comment]
For the sake of completeness in `poco-1.9.1` and `develop` branch, the cmake build is building PostgreSQL support in Poco. Also on MacOSX.
I think this issue is fixed.
